# Generated by Django 5.2.15 on 2026-06-28 11:37

from django.db import migrations, models


def delete_legacy_market_rows(apps, schema_editor):
    Market = apps.get_model("scheduler", "Market")
    Market.objects.filter(pricing_model="legacy").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_scale_share_market_seed_chips'),
    ]

    operations = [
        migrations.RunPython(delete_legacy_market_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='market',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='market',
            name='pricing_model',
        ),
        migrations.RemoveField(
            model_name='market',
            name='replacement',
        ),
        migrations.AlterField(
            model_name='chipbalanceevent',
            name='reason',
            field=models.CharField(choices=[('opening_balance', 'Opening balance'), ('daily_grant', 'Daily grant'), ('market_trade', 'Market trade'), ('market_payout', 'Market payout'), ('clicker_conversion', 'Beer-clicker conversion')], max_length=24),
        ),
    ]
